const views={temp:{title:'Temperature',subtitle:'Surface temperature forecast',icon:'☀',overlay:'temp',product:'gfs'},radar:{title:'Lightning Tracker',subtitle:'Live radar and lightning activity',icon:'ϟ',overlay:'radar',product:'radar'},fog:{title:'Fog',subtitle:'Fog and visibility conditions',icon:'≋',overlay:'fog',product:'gfs'},rain:{title:'Rain & Clouds',subtitle:'Rain, thunder and cloud forecast',icon:'☂',overlay:'rain',product:'gfs'},fishing:{title:'Fishing Lakes',subtitle:'Known fishing waters within 200 km',icon:'🎣'}};
const defaults={lat:50.4452,lon:-104.6189,name:'Regina',unit:'°C',view:'temp',range:'hourly',dark:true};let state;try{state={...defaults,...JSON.parse(localStorage.getItem('thunder-struck-settings')||'{}')}}catch{state={...defaults}}let forecast=null;
const $=s=>document.querySelector(s),map=$('#windyMap'),mapWrap=$('.map-wrap'),toast=$('#toast');let fishingMap,fishingLayer;const save=()=>localStorage.setItem('thunder-struck-settings',JSON.stringify(state));
function windyUrl(){const v=views[state.view],p=new URLSearchParams({lat:state.lat,lon:state.lon,detailLat:state.lat,detailLon:state.lon,width:1200,height:700,zoom:6,level:'surface',overlay:v.overlay,product:v.product,menu:'',message:'true',marker:'',calendar:'now',pressure:'',type:'map',location:'coordinates',detail:'',metricWind:'default',metricTemp:state.unit,radarRange:'-1'});return`https://embed.windy.com/embed2.html?${p}`}
function displayTemp(c){if(!Number.isFinite(c))return'--°';const n=state.unit==='°F'?c*9/5+32:c;return`${Math.round(n)}°`}
function symbol(code=0){if([95,96,99].includes(code))return'⛈️';if([71,73,75,77,85,86].includes(code))return'🌨️';if(code>=51&&code<=67||code>=80&&code<=82)return'🌧️';if(code===3)return'☁️';if(code===1||code===2)return'🌤️';if(code===45||code===48)return'🌫️';return'☀️'}
function condition(code=0){if([95,96,99].includes(code))return'Thunderstorms';if(code>=51&&code<=82)return'Precipitation';if(code===3)return'Cloudy';if(code===1||code===2)return'Partly Cloudy';if(code===45||code===48)return'Foggy';return'Clear'}
function weatherImage(code=0){if([95,96,99].includes(code))return'thunderstorm.svg';if([71,73,75,77,85,86].includes(code))return'snow.svg';if(code>=51&&code<=67||code>=80&&code<=82)return'rain.svg';if(code===3||code===45||code===48)return'cloudy.svg';if(code===1||code===2)return'partly-cloudy.svg';return'clear-day.svg'}
function renderForecast(){const strip=$('#forecastStrip');strip.innerHTML='';if(!forecast){$('#forecastNotice').classList.add('show');$('#forecastNotice').textContent='Loading no-key forecast data…';return}$('#forecastNotice').classList.remove('show');const d=forecast.daily,h=forecast.hourly,current=forecast.current;$('#currentWeatherImage').src=`../assets/weather/${weatherImage(current.weather_code)}`;$('#currentWeatherImage').alt=condition(current.weather_code);$('#currentTemp').textContent=displayTemp(current.temperature_2m);$('#currentCondition').textContent=condition(current.weather_code);$('#highLow').innerHTML=`H:${displayTemp(d.temperature_2m_max[0])} &nbsp; L:${displayTemp(d.temperature_2m_min[0])}`;const rain=d.precipitation_probability_max[0]||0;$('#daySummary').textContent=`${condition(d.weather_code[0])} conditions are expected today${rain?` with up to a ${rain}% chance of precipitation`:''}. Forecast data by Open-Meteo.`;let items=[];if(state.range==='hourly'){const start=Math.max(0,h.time.findIndex(t=>new Date(t)>=new Date()));items=h.time.slice(start,start+12).map((t,j)=>({label:new Date(t).toLocaleTimeString([],{hour:'numeric'}),temp:h.temperature_2m[start+j],code:h.weather_code[start+j]}))}else{const count=state.range==='daily'?5:7;items=d.time.slice(0,count).map((t,i)=>({label:new Date(`${t}T12:00`).toLocaleDateString([],{weekday:'short'}),temp:d.temperature_2m_max[i],code:d.weather_code[i]}))}items.forEach(x=>{const el=document.createElement('div');el.className='forecast-item';el.innerHTML=`<b>${x.label}</b><div class="weather-symbol">${symbol(x.code)}</div><span>${displayTemp(x.temp)}</span>`;strip.append(el)})}
async function loadForecast(silent=false){if(!silent){forecast=null;renderForecast()}try{const result=await window.thunderStruck.getForecast(state.lat,state.lon);forecast=result.data;renderForecast()}catch(e){if(silent)return;$('#forecastNotice').classList.add('show');$('#forecastNotice').textContent=`Forecast unavailable: ${e.message}`}}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lakePinSvg='<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg"><line class="pin-needle" x1="18" y1="19" x2="18" y2="34"/><path class="pin-collar" d="M13 17.2h10l-1.7 4.4h-6.6z"/><circle class="pin-head" cx="18" cy="10.4" r="8.2"/><circle class="pin-shine" cx="15" cy="7.6" r="2.4"/></svg>';
const lakeIcon=active=>L.divIcon({className:'lake-pin-wrap',html:`<div class="lake-pin${active?' active':''}">${lakePinSvg}</div>`,iconSize:[36,36],iconAnchor:[18,34],popupAnchor:[0,-30]});
function kmBetween(aLat,aLon,bLat,bLon){const r=Math.PI/180,dLat=(bLat-aLat)*r,dLon=(bLon-aLon)*r,h=Math.sin(dLat/2)**2+Math.cos(aLat*r)*Math.cos(bLat*r)*Math.sin(dLon/2)**2;return 6371*2*Math.asin(Math.sqrt(h))}
const fmtKm=d=>`${d.toFixed(d<10?1:0)} km away`;
const MIN_FISH_ZOOM=6,SEARCH_KM=200;let lakes=[],lakeMarkers=new Map(),selectedLakeId=null,lakesSeq=0,moveTimer=null,fishSeq=0,searchCircle=null;
const fishFallbackImg='data:image/svg+xml;utf8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect width="48" height="48" rx="9" fill="#12314e"/><path d="M8 24c5-7 12-10 19-10 6 0 10 4 12 7l5-5v16l-5-5c-2 3-6 7-12 7-7 0-14-3-19-10z" fill="#5fb3e8"/><circle cx="30" cy="21" r="1.8" fill="#0a1a2b"/></svg>');
const BAIT_GUIDE=[
 {match:/walleye|sauger|pickerel|zander/i,tips:['Jig (1/8–3/8 oz) tipped with a live minnow or leech','Bottom bouncer with a spinner + nightcrawler harness','Deep-diving crankbaits trolled along drop-offs at dusk','Soft plastic paddle-tails on a jig head']},
 {match:/northern pike|muskellunge|muskie|pike/i,tips:['Large spoons (e.g. red/white 5 of Diamonds style)','Inline spinners and bucktails','Spinnerbaits worked over weed edges','Dead bait (smelt/cisco) on a quick-strike rig','Always use a wire or heavy fluorocarbon leader']},
 {match:/yellow perch|perch/i,tips:['Small jigs (1/16–1/32 oz) tipped with a piece of worm','Small minnows under a slip bobber','Tiny jigging spoons with waxworms through the ice']},
 {match:/lake trout/i,tips:['Heavy jigging spoons and tube jigs fished deep','Trolled spoons behind downriggers in summer','White soft-plastic swimbaits near bottom']},
 {match:/rainbow|brown trout|brook|cutthroat|tiger trout|trout/i,tips:['Small inline spinners (Mepps/Panther Martin style)','Small spoons in silver or gold','Dough bait (PowerBait) for stocked waters, floated off bottom','Worms under a bobber; flies (leeches, nymphs) work well too']},
 {match:/whitefish|cisco|tullibee/i,tips:['Small jigging spoons tipped with waxworms or maggots','Tiny jigs fished near bottom','Wire worms / small flies through the ice']},
 {match:/burbot|ling|mariah/i,tips:['Glow-in-the-dark jigs tipped with cut bait, fished at night','Heavy spoons rattled on bottom','Dead minnows or cut sucker on a bottom rig']},
 {match:/smallmouth/i,tips:['Ned rigs and tube jigs on rocky bottoms','Small crankbaits and jerkbaits','Topwater poppers early and late','Drop-shot with soft plastic minnows']},
 {match:/largemouth|bass/i,tips:['Soft plastic worms (Texas rig) around cover','Spinnerbaits and chatterbaits along weed lines','Topwater frogs over vegetation','Jig-and-craw combos near structure']},
 {match:/crappie/i,tips:['Small tube jigs (1/16 oz) in bright colours','Live minnows under a slip bobber','Slowly trolled mini crankbaits']},
 {match:/bluegill|pumpkinseed|sunfish|rock bass/i,tips:['Piece of worm on a small hook under a bobber','Tiny jigs with waxworms','Small poppers on light line']},
 {match:/carp/i,tips:['Canned sweet corn on a hair rig','Boilies or dough baits','Bread crust fished on the surface in calm water']},
 {match:/catfish|bullhead/i,tips:['Cut bait or chicken liver on a bottom rig','Nightcrawlers fished on bottom','Prepared stink baits in warm water']},
 {match:/goldeye|mooneye/i,tips:['Small spinners and spoons','Pieces of worm drifted in current','Small flies near the surface in the evening']},
 {match:/sucker|redhorse|quillback|buffalo/i,tips:['Nightcrawlers fished right on bottom','Small pieces of worm on a hook with light split shot']},
 {match:/sturgeon/i,tips:['Nightcrawler bundles or cut bait on a heavy bottom rig','Check local regulations — often catch-and-release only']}];
const genericBait=['Live worms or minnows under a bobber','Small jigs and spinners in natural colours','Ask a local tackle shop what is producing right now'];
const baitFor=name=>{const hit=BAIT_GUIDE.find(g=>g.match.test(name));return hit?hit.tips:genericBait};
function closeFishPanel(){$('#fishPanel').classList.remove('open')}
function renderBaitDetail(fish,lakeName){const body=$('#fishBody');body.innerHTML='';const back=document.createElement('button');back.className='fish-back';back.textContent='‹ Back to fish list';back.onclick=()=>{const lake=lakes.find(x=>x.id===selectedLakeId);if(lake)openFishPanel(lake)};const head=document.createElement('div');head.className='fish-detail-head';head.innerHTML=`<img src="${esc(fish.photo||fishFallbackImg)}" alt=""><div><b>${esc(fish.name)}</b>${fish.sci?`<small>${esc(fish.sci)}</small>`:''}</div>`;const label=document.createElement('p');label.className='bait-label';label.textContent='Best baits & lures';const ul=document.createElement('ul');ul.className='bait-list';baitFor(`${fish.name} ${fish.sci||''}`).forEach(t=>{const li=document.createElement('li');li.textContent=t;ul.append(li)});const note=document.createElement('p');note.className='fish-note';note.textContent='General guidance — check local regulations for bait and gear restrictions.';body.append(back,head,label,ul,note);$('#fishPanelTitle').textContent=lakeName}
function renderFishList(fishes,lake,noteText){const body=$('#fishBody');body.innerHTML='';$('#fishPanelTitle').textContent=lake.name;if(noteText){const n=document.createElement('p');n.className='fish-note';n.textContent=noteText;body.append(n)}fishes.forEach(f=>{const b=document.createElement('button');b.className='fish-item';const img=document.createElement('img');img.src=f.photo||fishFallbackImg;img.alt='';img.onerror=()=>{img.onerror=null;img.src=fishFallbackImg};const txt=document.createElement('div');txt.innerHTML=`<b>${esc(f.name)}</b>${f.sci?`<small>${esc(f.sci)}</small>`:''}`;b.append(img,txt);b.onclick=()=>renderBaitDetail(f,lake.name);body.append(b)})}
const REGIONAL_FALLBACK=[{name:'Walleye',sci:'Sander vitreus'},{name:'Northern Pike',sci:'Esox lucius'},{name:'Yellow Perch',sci:'Perca flavescens'},{name:'Lake Whitefish',sci:'Coregonus clupeaformis'},{name:'Burbot',sci:'Lota lota'},{name:'Rainbow Trout',sci:'Oncorhynchus mykiss'}];
async function openFishPanel(lake){const panel=$('#fishPanel');panel.classList.add('open');$('#fishPanelTitle').textContent=lake.name;$('#fishBody').innerHTML='<div class="lake-empty">Looking up recorded fish species…</div>';const seq=++fishSeq;try{const fishes=await window.thunderStruck.getLakeFish(lake.lat,lake.lon);if(seq!==fishSeq)return;if(fishes.length)renderFishList(fishes,lake,'Species recorded near this water (iNaturalist observations). Tap a fish for bait & lure tips.');else renderFishList(REGIONAL_FALLBACK,lake,'No recorded observations for this water — showing common regional species instead. Verify locally.')}catch{if(seq!==fishSeq)return;renderFishList(REGIONAL_FALLBACK,lake,'Species lookup unavailable — showing common regional species instead. Verify locally.')}}
function selectLake(id,pan){selectedLakeId=id;lakeMarkers.forEach((m,mid)=>m.setIcon(lakeIcon(mid===id)));document.querySelectorAll('.lake-item').forEach(el=>el.classList.toggle('selected',el.dataset.lake===id));document.querySelector(`.lake-item[data-lake="${CSS.escape(id)}"]`)?.scrollIntoView({block:'nearest'});const m=lakeMarkers.get(id);if(m){if(pan)fishingMap.panTo(m.getLatLng());m.openPopup()}const lake=lakes.find(x=>x.id===id);if(lake)openFishPanel(lake)}
function renderLakePanel(){const list=$('#lakeList');list.innerHTML='';$('#lakeCount').textContent=lakes.length?`${lakes.length} found`:'';if(!lakes.length){list.innerHTML=`<div class="lake-empty">${fishingMap&&fishingMap.getZoom()<MIN_FISH_ZOOM?'Zoom in on an area of the map to find fishing waters there.':'No mapped fishing waters found in this area. Pan or zoom to explore.'}</div>`;return}lakes.forEach(x=>{const b=document.createElement('button');b.className='lake-item';b.dataset.lake=x.id;if(x.id===selectedLakeId)b.classList.add('selected');b.innerHTML=`<b>${esc(x.name)}</b><small>${fmtKm(x.dist)}${x.fishing!=='unverified'?' · '+esc(x.fishing):''}</small>`;b.onclick=()=>selectLake(x.id,true);list.append(b)})}
async function refreshLakes(){if(!fishingMap)return;if(fishingMap.getZoom()<MIN_FISH_ZOOM){lakesSeq++;lakes=[];lakeMarkers.clear();fishingLayer.clearLayers();searchCircle=null;selectedLakeId=null;closeFishPanel();renderLakePanel();$('#updatedText').textContent='Zoom in to load fishing waters';return}const seq=++lakesSeq;const c=fishingMap.getCenter();if(!searchCircle){searchCircle=L.circle([c.lat,c.lng],{radius:SEARCH_KM*1000,color:'#f5c542',weight:1.5,dashArray:'6 8',fill:false,interactive:false}).addTo(fishingLayer)}else searchCircle.setLatLng([c.lat,c.lng]);$('#updatedText').textContent=`Searching within ${SEARCH_KM} km…`;try{const raw=await window.thunderStruck.getFishingLakes({lat:c.lat,lon:c.lng});if(seq!==lakesSeq)return;const byName=new Map();raw.forEach(x=>{x.dist=kmBetween(c.lat,c.lng,x.lat,x.lon);if(x.dist>SEARCH_KM)return;const key=(x.name||'').toLowerCase();const prev=byName.get(key);if(!prev||(x.major&&!prev.major)||(x.major===prev.major&&x.dist<prev.dist))byName.set(key,x)});lakes=[...byName.values()].sort((a,b2)=>a.dist-b2.dist).slice(0,300);const keep=new Set(lakes.map(x=>x.id));lakeMarkers.forEach((m,id)=>{if(!keep.has(id)){fishingLayer.removeLayer(m);lakeMarkers.delete(id)}});lakes.forEach(x=>{if(lakeMarkers.has(x.id))return;const m=L.marker([x.lat,x.lon],{icon:lakeIcon(x.id===selectedLakeId),title:x.name}).bindPopup(`<b>${esc(x.name)}</b><br><small>${x.fishing==='unverified'?'Verify fish species and local regulations':'Fishing: '+esc(x.fishing)}</small>`).on('click',()=>selectLake(x.id,false)).addTo(fishingLayer);lakeMarkers.set(x.id,m)});if(selectedLakeId&&!keep.has(selectedLakeId)){selectedLakeId=null;closeFishPanel()}renderLakePanel();$('#updatedText').textContent=`${lakes.length} fishing waters within ${SEARCH_KM} km`}catch(e){if(seq!==lakesSeq)return;$('#lakeList').innerHTML='<div class="lake-empty">Lake data is temporarily unavailable. Check your connection and try again.</div>';$('#updatedText').textContent='Lake data unavailable';showToast(e.message)}}
function loadFishing(){map.style.display='none';$('#fishingMap').style.display='block';$('#fishingPanel').classList.add('open');mapWrap.classList.add('loaded');if(!fishingMap){fishingMap=L.map('fishingMap').setView([state.lat,state.lon],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(fishingMap);fishingLayer=L.layerGroup().addTo(fishingMap);fishingMap.on('moveend',()=>{clearTimeout(moveTimer);moveTimer=setTimeout(refreshLakes,450)})}else{fishingMap.setView([state.lat,state.lon],Math.max(fishingMap.getZoom(),9))}setTimeout(()=>{fishingMap.invalidateSize();refreshLakes()},100)}
function render(reload=true){document.body.classList.toggle('light',!state.dark);$('#placeName').textContent=state.name;const v=views[state.view];$('#viewTitle').textContent=v.title;$('#viewSubtitle').textContent=v.subtitle;const icon=$('#viewIcon');icon.textContent=v.icon;icon.className=`view-icon ${state.view==='radar'?'lightning':state.view}`;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',b.dataset.range===state.range));if(state.view==='fishing'){$('#sourcePill').innerHTML='<i></i> OPEN DATA';$('#mapCredit').innerHTML='Fishing waters from <strong>OpenStreetMap contributors</strong>';loadFishing()}else{$('#sourcePill').innerHTML='<i></i> WINDY LIVE';$('#mapCredit').innerHTML='Weather visualization by <strong>Windy.com</strong>';$('#fishingMap').style.display='none';$('#fishingPanel').classList.remove('open');$('#fishPanel').classList.remove('open');map.style.display='block';if(reload){mapWrap.classList.remove('loaded');map.src=windyUrl()}}renderForecast()}
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}
map.addEventListener('load',()=>{mapWrap.classList.add('loaded');$('#updatedText').textContent=`Loaded ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render()});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{state.range=b.dataset.range;save();renderForecast();document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b))});
const results=$('#searchResults');let searchSeq=0;async function search(){const q=$('#searchInput').value.trim();if(q.length<2)return;const seq=++searchSeq;if(!results.children.length)results.innerHTML='<button>Searching…</button>';results.classList.add('open');try{const places=await window.thunderStruck.searchLocations(q);if(seq!==searchSeq)return;results.innerHTML='';places.forEach(p=>{const b=document.createElement('button');b.textContent=p.name;b.onclick=()=>{state.lat=p.lat;state.lon=p.lon;state.name=p.name.split(',')[0];save();results.classList.remove('open');$('#searchInput').value='';render();loadForecast()};results.append(b)});if(!places.length)results.innerHTML='<button>No locations found</button>'}catch{if(seq===searchSeq)results.innerHTML='<button>Location search unavailable</button>'}}$('#searchButton').onclick=search;$('#searchInput').onkeydown=e=>{if(e.key==='Enter'){clearTimeout(searchTimer);search()}};let searchTimer;$('#searchInput').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(q.length<2){results.classList.remove('open');results.innerHTML='';return}searchTimer=setTimeout(search,350)});document.addEventListener('click',e=>{if(!e.target.closest('.search'))results.classList.remove('open')});
$('#locateButton').onclick=async()=>{const p=await window.thunderStruck.getPermissions();if(!p.location)return showToast('Enable Location under Settings → Permissions');const useLocation=async loc=>{state.lat=loc.lat;state.lon=loc.lon;state.name=loc.name||'My Location';save();await window.thunderStruck.setAlertLocation({lat:state.lat,lon:state.lon});$('#fishPanelClose').onclick=closeFishPanel;
$('#appVersion').textContent=`v${window.thunderStruck.version}`;
setInterval(()=>loadForecast(true),60*1000);
render();loadForecast();if(loc.approximate)showToast('Using approximate network location')};navigator.geolocation?.getCurrentPosition(pos=>useLocation({lat:pos.coords.latitude,lon:pos.coords.longitude,name:'My Location'}),async()=>{try{await useLocation(await window.thunderStruck.getApproxLocation())}catch{showToast('Turn on Location Services in Windows Settings → Privacy & security → Location')}})};
const settings=$('#settingsDialog');$('#settingsButton').onclick=async()=>{document.querySelectorAll('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===state.unit));$('#themeToggle').setAttribute('aria-pressed',String(state.dark));const p=await window.thunderStruck.getPermissions();$('#locationPermission').setAttribute('aria-pressed',String(p.location));$('#notificationPermission').setAttribute('aria-pressed',String(p.notifications));settings.showModal()};document.querySelectorAll('.switch').forEach(b=>b.onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')==='true';e.currentTarget.setAttribute('aria-pressed',String(!on))});document.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-settings]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-settings-panel]').forEach(p=>p.hidden=p.dataset.settingsPanel!==b.dataset.settings)});document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>document.querySelectorAll('[data-unit]').forEach(x=>x.classList.toggle('active',x===b)));$('#saveSettings').onclick=async()=>{state.dark=$('#themeToggle').getAttribute('aria-pressed')==='true';state.unit=document.querySelector('[data-unit].active').dataset.unit;await window.thunderStruck.setPermissions({location:$('#locationPermission').getAttribute('aria-pressed')==='true',notifications:$('#notificationPermission').getAttribute('aria-pressed')==='true'});save();settings.close();render();loadForecast()};
$('#checkUpdates').onclick=async()=>{const d=$('#updateDialog');$('#updateTitle').textContent='Checking for Updates…';$('#updateMessage').textContent='Contacting GitHub releases.';$('#updateActions').innerHTML='';d.showModal();try{const u=await window.thunderStruck.checkForUpdates();if(u.found){$('#updateTitle').textContent='Update Found';$('#updateMessage').textContent=u.hasInstaller?`Thunder Struck ${u.version} is ready to download.`:`Thunder Struck ${u.version} was released, but no installer (.exe) is attached — opening the release page instead.`;$('#updateActions').innerHTML='<button id="downloadUpdate" type="button" class="primary">Download</button><button value="cancel" class="secondary">Close</button>';$('#downloadUpdate').onclick=async()=>{await window.thunderStruck.downloadUpdate(u.url);d.close();showToast('Update download started')}}else{$('#updateTitle').textContent='No Updates Found';$('#updateMessage').textContent=u.reason||'You already have the latest version.';$('#updateActions').innerHTML='<button value="ok" class="primary">OK</button>'}}catch(e){$('#updateTitle').textContent='Update Check Failed';$('#updateMessage').textContent='Make sure the GitHub repository is public and has a published Release.';$('#updateActions').innerHTML='<button value="ok" class="primary">OK</button>'}};
$('#fishPanelClose').onclick=closeFishPanel;
$('#appVersion').textContent=`v${window.thunderStruck.version}`;
setInterval(()=>loadForecast(true),60*1000);
render();loadForecast();
